logging:
    level:
        root: info
        com.jaewoo.batch: debug

spring:
    batch:
        job:
            names: ${job.name:NONE}
    output:
        ansi:
            enabled: always
    jpa:
        hibernate:
            ddl-auto: update
            use-new-id-generator-mappings: true
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    datasource:
        url: jdbc:mysql://localhost:3306/batch?serverTimezone=Asia/Seoul
        username: batch
        password: batch
